### ISSUE TITLE
-soname should not be used for OS X build

### ISSUE THREAD

**Issue by elfprince13** [arsf/LAStools#6]
The readme claims that the Makefiles should work for Mac builds; however, the -soname flag is incorrect for creating dynamic libraries on OS X.

**Comment by elfprince13** [comment]
See https://github.com/arsf/LAStools/blob/master/LASlib/src/Makefile#L36

**Comment by danclewley** [comment]
Thanks for pointing this out. 
This is a fork of the official version of LAStools (https://github.com/LAStools/LAStools) with so will inherit the readme from this. It has mainly been tested under Linux. Unless you need to use the ARSF fork (e.g., to build ARSF software such as [LAG](https://github.com/arsf/lag)) we recommend using the official version. Although as Martin points out [here](https://github.com/LAStools/LAStools/issues/9) this doesn't build dynamic libraries.

**Comment by danclewley** [comment]
Have added a new readme clarifying this fork is for NERC-ARF-DAN Linux systems or for building LAG against (currently Linux only).

Closing as an issue has been opened on the official version of LAStools - although it doesn't look like there are plans to add building dynamic libraries on OS X or Linux.
